### ISSUE TITLE
remove rocksdb dependency

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#155]
sc-service was changed to `default-features = true` to add support for rocksdb because I hit this issue https://github.com/sunshine-protocol/sunshine-bounty/issues/150

I would much prefer removing rocksdb but I also want to be able to run a node

**Comment by 4meta5** [comment]
This change broke all of the subxt tests

```
failures:

---- org::tests::simple_test stdout ----
thread 'org::tests::simple_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- org::tests::register_flat_org_test stdout ----
thread 'org::tests::register_flat_org_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::simple_test stdout ----
thread 'bounty::tests::simple_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::get_bounties_test stdout ----
thread 'bounty::tests::get_bounties_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bounty::tests::contribute_to_bounty_test stdout ----
thread 'bounty::tests::contribute_to_bounty_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::post_bounty_test stdout ----
thread 'bounty::tests::post_bounty_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51


failures:
    bounty::tests::contribute_to_bounty_test
    bounty::tests::get_bounties_test
    bounty::tests::post_bounty_test
    bounty::tests::simple_test
    org::tests::register_flat_org_test
    org::tests::simple_test

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by 4meta5** [comment]
All my substrate-subxt tests are failing now because the rocksdb feature is no longer enabled.

```
---- bounty::tests::get_bounties_test stdout ----
thread 'bounty::tests::get_bounties_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::contribute_to_bounty_test stdout ----
thread 'bounty::tests::contribute_to_bounty_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::simple_test stdout ----
thread 'bounty::tests::simple_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- org::tests::simple_test stdout ----
thread 'org::tests::simple_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- bounty::tests::post_bounty_test stdout ----
thread 'bounty::tests::post_bounty_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51

---- org::tests::register_flat_org_test stdout ----
thread 'org::tests::register_flat_org_test' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Backend("`with-kvdb-rocksdb` feature not enabled, database can not be opened"))', /Users/4meta5/.cargo/git/checkouts/sunshine-core-b646449ae6936647/b15fa47/client/src/mock.rs:40:51


failures:
    bounty::tests::contribute_to_bounty_test
    bounty::tests::get_bounties_test
    bounty::tests::post_bounty_test
    bounty::tests::simple_test
    org::tests::register_flat_org_test
    org::tests::simple_test

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```
